Apr 17 14:29:19 servera polkitd[845]: Loading rules from directory /etc/polkit-1/rules.d
Apr 17 14:29:19 servera polkitd[845]: Loading rules from directory /usr/share/polkit-1/rules.d
Apr 17 14:29:19 servera polkitd[845]: Finished loading, compiling and executing 4 rules
Apr 17 14:29:19 servera polkitd[845]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Apr 17 14:29:21 servera sshd[901]: Server listening on 0.0.0.0 port 22.
Apr 17 14:29:21 servera sshd[901]: Server listening on :: port 22.
Apr 17 14:39:19 servera sshd[1182]: Accepted publickey for devops from 172.25.250.9 port 50616 ssh2: RSA SHA256:M8ikhcEDm2tQ95Z0o7ZvufqEixCFCt+wowZLNzNlBT0
Apr 17 14:39:19 servera systemd[1186]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Apr 17 14:39:19 servera sshd[1182]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Apr 17 14:39:20 servera sudo[1319]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tszltuktzgtogynazgyfqhnzvfsadtpb ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650220759.4340634-2716-237003249048824/AnsiballZ_setup.py
Apr 17 14:39:20 servera sudo[1319]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:39:20 servera sudo[1319]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:39:20 servera sudo[1319]: pam_unix(sudo:session): session closed for user root
Apr 17 14:39:21 servera sudo[1462]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dygybymsrjjvirclcdvubsmlcqlugdxf ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650220761.2563515-2734-88654927840965/AnsiballZ_dnf.py
Apr 17 14:39:21 servera sudo[1462]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:39:21 servera sudo[1462]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:39:23 servera sudo[1462]: pam_unix(sudo:session): session closed for user root
Apr 17 14:39:24 servera sudo[1574]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-pihjaavgeyaamtcftvdghpmvjndgsims ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650220763.941608-2743-239967893552950/AnsiballZ_systemd.py
Apr 17 14:39:24 servera sudo[1574]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:39:24 servera sudo[1574]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:39:25 servera sudo[1574]: pam_unix(sudo:session): session closed for user root
Apr 17 14:40:25 servera sshd[1197]: Received disconnect from 172.25.250.9 port 50616:11: disconnected by user
Apr 17 14:40:25 servera sshd[1197]: Disconnected from user devops 172.25.250.9 port 50616
Apr 17 14:40:25 servera sshd[1182]: pam_unix(sshd:session): session closed for user devops
Apr 17 14:40:25 servera systemd[1190]: pam_unix(systemd-user:session): session closed for user devops
Apr 17 14:42:20 servera sshd[1738]: Accepted publickey for devops from 172.25.250.9 port 50618 ssh2: RSA SHA256:M8ikhcEDm2tQ95Z0o7ZvufqEixCFCt+wowZLNzNlBT0
Apr 17 14:42:20 servera systemd[1742]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Apr 17 14:42:20 servera sshd[1738]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Apr 17 14:42:20 servera sudo[1874]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-blerzbzsqhenxuiscgvakkqrfzwezxej ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650220940.4979496-2815-111124931180760/AnsiballZ_setup.py
Apr 17 14:42:20 servera sudo[1874]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:42:20 servera sudo[1874]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:42:21 servera sudo[1874]: pam_unix(sudo:session): session closed for user root
Apr 17 14:42:21 servera sudo[2017]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-soiwnninstudtoyujblilgeggfjxxpba ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650220941.496628-2830-39526348397741/AnsiballZ_command.py
Apr 17 14:42:21 servera sudo[2017]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:42:21 servera sudo[2017]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:42:21 servera sudo[2017]: pam_unix(sudo:session): session closed for user root
Apr 17 14:42:22 servera sudo[2127]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dsbeeyoqfyttrknkqhwchjixanrfcdkg ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650220942.060783-2841-224781303956002/AnsiballZ_dnf.py
Apr 17 14:42:22 servera sudo[2127]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:42:22 servera sudo[2127]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:42:23 servera sudo[2127]: pam_unix(sudo:session): session closed for user root
Apr 17 14:42:23 servera sudo[2236]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tqaqakcvqiouciornjvojriuwzqnhvoj ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650220943.5847447-2850-43857559640708/AnsiballZ_systemd.py
Apr 17 14:42:23 servera sudo[2236]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:42:23 servera sudo[2236]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:42:24 servera sudo[2236]: pam_unix(sudo:session): session closed for user root
Apr 17 14:43:24 servera sshd[1752]: Received disconnect from 172.25.250.9 port 50618:11: disconnected by user
Apr 17 14:43:24 servera sshd[1752]: Disconnected from user devops 172.25.250.9 port 50618
Apr 17 14:43:24 servera sshd[1738]: pam_unix(sshd:session): session closed for user devops
Apr 17 14:43:24 servera systemd[1746]: pam_unix(systemd-user:session): session closed for user devops
Apr 17 14:43:27 servera sshd[2271]: Accepted publickey for devops from 172.25.250.9 port 50620 ssh2: RSA SHA256:M8ikhcEDm2tQ95Z0o7ZvufqEixCFCt+wowZLNzNlBT0
Apr 17 14:43:27 servera systemd[2275]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Apr 17 14:43:27 servera sshd[2271]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Apr 17 14:43:28 servera sudo[2407]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vddsvpwuhsvbxfmvcuhjsexxmnwczmlb ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221007.9849186-2880-251417922742733/AnsiballZ_setup.py
Apr 17 14:43:28 servera sudo[2407]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:43:28 servera sudo[2407]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:43:28 servera sudo[2407]: pam_unix(sudo:session): session closed for user root
Apr 17 14:43:29 servera sudo[2550]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-cvwvxcygygfeuyplbkxyiamdokjdehge ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221008.9695563-2895-180611439891126/AnsiballZ_command.py
Apr 17 14:43:29 servera sudo[2550]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:43:29 servera sudo[2550]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:43:29 servera sudo[2550]: pam_unix(sudo:session): session closed for user root
Apr 17 14:43:29 servera sudo[2660]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-anilmvbaqyspsjyefbysduwkfmrihuvi ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221009.5566182-2906-210416522988655/AnsiballZ_dnf.py
Apr 17 14:43:29 servera sudo[2660]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:43:29 servera sudo[2660]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:43:30 servera sudo[2660]: pam_unix(sudo:session): session closed for user root
Apr 17 14:43:31 servera sudo[2769]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-unargvlkewcitefcolhqsmoksymqfrfb ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221011.0356271-2915-50497601734579/AnsiballZ_systemd.py
Apr 17 14:43:31 servera sudo[2769]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:43:31 servera sudo[2769]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:43:31 servera sudo[2769]: pam_unix(sudo:session): session closed for user root
Apr 17 14:43:57 servera sudo[2914]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-pxrhlcmzieujjwashgrnrveuarqziexk ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221036.7667258-2954-36861150983247/AnsiballZ_setup.py
Apr 17 14:43:57 servera sudo[2914]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:43:57 servera sudo[2914]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:43:57 servera sudo[2914]: pam_unix(sudo:session): session closed for user root
Apr 17 14:43:58 servera sudo[3057]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-opnvqhldvwfgisbrducbddjwulmndhwi ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221037.7957988-2965-245262900346828/AnsiballZ_command.py
Apr 17 14:43:58 servera sudo[3057]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:43:58 servera sudo[3057]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:43:58 servera sudo[3057]: pam_unix(sudo:session): session closed for user root
Apr 17 14:43:58 servera sudo[3167]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-faholhumqymrukrnsrafcltlyokziufu ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221038.3853142-2976-33538413445033/AnsiballZ_dnf.py
Apr 17 14:43:58 servera sudo[3167]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:43:58 servera sudo[3167]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:43:59 servera sudo[3167]: pam_unix(sudo:session): session closed for user root
Apr 17 14:44:00 servera sudo[3276]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ohewfhpsbtaqbpqxyvzuyhbnhoapsnnb ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221039.8322434-2985-223066912201309/AnsiballZ_systemd.py
Apr 17 14:44:00 servera sudo[3276]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:44:00 servera sudo[3276]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:44:00 servera sudo[3276]: pam_unix(sudo:session): session closed for user root
Apr 17 14:45:00 servera sshd[2285]: Received disconnect from 172.25.250.9 port 50620:11: disconnected by user
Apr 17 14:45:00 servera sshd[2285]: Disconnected from user devops 172.25.250.9 port 50620
Apr 17 14:45:00 servera sshd[2271]: pam_unix(sshd:session): session closed for user devops
Apr 17 14:45:00 servera systemd[2279]: pam_unix(systemd-user:session): session closed for user devops
Apr 17 14:45:24 servera sshd[3313]: Accepted publickey for devops from 172.25.250.9 port 50622 ssh2: RSA SHA256:M8ikhcEDm2tQ95Z0o7ZvufqEixCFCt+wowZLNzNlBT0
Apr 17 14:45:24 servera systemd[3317]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Apr 17 14:45:24 servera sshd[3313]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Apr 17 14:45:24 servera sudo[3449]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ipuezzruwbluolplmdmgagifhqhkzera ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221124.3403344-3035-168828532891588/AnsiballZ_setup.py
Apr 17 14:45:24 servera sudo[3449]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:45:24 servera sudo[3449]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:45:25 servera sudo[3449]: pam_unix(sudo:session): session closed for user root
Apr 17 14:45:25 servera sudo[3592]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vbrjelskvjkbayctgjkmrntulihydvzt ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221125.350941-3050-39667672772919/AnsiballZ_command.py
Apr 17 14:45:25 servera sudo[3592]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:45:25 servera sudo[3592]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:45:25 servera sudo[3592]: pam_unix(sudo:session): session closed for user root
Apr 17 14:45:26 servera sudo[3702]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tlkeirzjjraqsljmokiejkljeyzaepic ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221125.9215777-3061-194965942404713/AnsiballZ_dnf.py
Apr 17 14:45:26 servera sudo[3702]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:45:26 servera sudo[3702]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:45:27 servera sudo[3702]: pam_unix(sudo:session): session closed for user root
Apr 17 14:45:27 servera sudo[3811]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wqvvlmypnbkgdrddykqqxgqoqxmrxijd ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221127.5281608-3070-67328129624283/AnsiballZ_dnf.py
Apr 17 14:45:27 servera sudo[3811]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:45:27 servera sudo[3811]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:45:28 servera sudo[3811]: pam_unix(sudo:session): session closed for user root
Apr 17 14:45:29 servera sudo[3920]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tznuhwfsdgcvdqvoeqjnvvdnzqrclwkr ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221128.8947203-3079-27283326545498/AnsiballZ_systemd.py
Apr 17 14:45:29 servera sudo[3920]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:45:29 servera sudo[3920]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:45:29 servera sudo[3920]: pam_unix(sudo:session): session closed for user root
Apr 17 14:46:03 servera sudo[4065]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kkdilpazjphdggcisqfztzxvyzolfkut ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221163.1225834-3109-103881152863809/AnsiballZ_setup.py
Apr 17 14:46:03 servera sudo[4065]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:46:03 servera sudo[4065]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:46:03 servera sudo[4065]: pam_unix(sudo:session): session closed for user root
Apr 17 14:46:04 servera sudo[4208]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vlovpkyscsuefoapwniighcrfpfxazqx ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221164.0767653-3120-101242423718948/AnsiballZ_command.py
Apr 17 14:46:04 servera sudo[4208]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:46:04 servera sudo[4208]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:46:04 servera sudo[4208]: pam_unix(sudo:session): session closed for user root
Apr 17 14:46:04 servera sudo[4318]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ozowngyyysidmoxvlrcyujppwvwhxuvs ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221164.6419442-3131-78756283539352/AnsiballZ_dnf.py
Apr 17 14:46:04 servera sudo[4318]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:46:04 servera sudo[4318]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:46:05 servera sudo[4318]: pam_unix(sudo:session): session closed for user root
Apr 17 14:46:06 servera sudo[4427]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-iyicpwzpxwslskzzzqzvuwzkgvsidolg ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221166.0481262-3140-85587715556605/AnsiballZ_dnf.py
Apr 17 14:46:06 servera sudo[4427]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:46:06 servera sudo[4427]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:46:07 servera sudo[4427]: pam_unix(sudo:session): session closed for user root
Apr 17 14:46:07 servera sudo[4536]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-smwnpaolrfurjueqhyhrophmgwjmento ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1650221167.315046-3149-32822289491372/AnsiballZ_systemd.py
Apr 17 14:46:07 servera sudo[4536]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Apr 17 14:46:07 servera sudo[4536]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Apr 17 14:46:07 servera sudo[4536]: pam_unix(sudo:session): session closed for user root
Apr 17 14:47:07 servera sshd[3327]: Received disconnect from 172.25.250.9 port 50622:11: disconnected by user
Apr 17 14:47:07 servera sshd[3327]: Disconnected from user devops 172.25.250.9 port 50622
Apr 17 14:47:07 servera sshd[3313]: pam_unix(sshd:session): session closed for user devops
Apr 17 14:47:07 servera systemd[3321]: pam_unix(systemd-user:session): session closed for user devops
Apr 17 14:47:27 servera sshd[4570]: error: kex_exchange_identification: client sent invalid protocol identifier "brain"
Apr 17 14:47:27 servera sshd[4570]: error: send_error: write: Broken pipe
Apr 17 14:47:28 servera sshd[4571]: Accepted publickey for root from 172.25.250.9 port 50632 ssh2: RSA SHA256:M8ikhcEDm2tQ95Z0o7ZvufqEixCFCt+wowZLNzNlBT0
Apr 17 14:47:28 servera systemd[4575]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Apr 17 14:47:28 servera sshd[4571]: pam_unix(sshd:session): session opened for user root by (uid=0)
Apr 17 14:47:33 servera sshd[4585]: Received disconnect from 172.25.250.9 port 50632:11: disconnected by user
Apr 17 14:47:33 servera sshd[4585]: Disconnected from user root 172.25.250.9 port 50632
Apr 17 14:47:33 servera sshd[4571]: pam_unix(sshd:session): session closed for user root
Apr 17 14:47:34 servera sshd[4645]: Accepted publickey for root from 172.25.250.9 port 50634 ssh2: RSA SHA256:M8ikhcEDm2tQ95Z0o7ZvufqEixCFCt+wowZLNzNlBT0
Apr 17 14:47:34 servera systemd[4659]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Apr 17 14:47:34 servera sshd[4645]: pam_unix(sshd:session): session opened for user root by (uid=0)
Apr 17 14:47:36 servera sshd[4669]: Received disconnect from 172.25.250.9 port 50634:11: disconnected by user
Apr 17 14:47:36 servera sshd[4669]: Disconnected from user root 172.25.250.9 port 50634
Apr 17 14:47:36 servera sshd[4645]: pam_unix(sshd:session): session closed for user root
Apr 18 01:58:38 servera polkitd[843]: Loading rules from directory /etc/polkit-1/rules.d
Apr 18 01:58:38 servera polkitd[843]: Loading rules from directory /usr/share/polkit-1/rules.d
Apr 18 01:58:38 servera polkitd[843]: Finished loading, compiling and executing 4 rules
Apr 18 01:58:38 servera polkitd[843]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Apr 18 01:58:40 servera sshd[902]: Server listening on 0.0.0.0 port 22.
Apr 18 01:58:40 servera sshd[902]: Server listening on :: port 22.
Apr 18 03:07:53 servera polkitd[836]: Loading rules from directory /etc/polkit-1/rules.d
Apr 18 03:07:53 servera polkitd[836]: Loading rules from directory /usr/share/polkit-1/rules.d
Apr 18 03:07:53 servera polkitd[836]: Finished loading, compiling and executing 4 rules
Apr 18 03:07:53 servera polkitd[836]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Apr 18 03:07:55 servera sshd[889]: Server listening on 0.0.0.0 port 22.
Apr 18 03:07:55 servera sshd[889]: Server listening on :: port 22.
Apr 18 03:09:55 servera sshd[1169]: error: kex_exchange_identification: client sent invalid protocol identifier "brain"
Apr 18 03:09:55 servera sshd[1169]: error: send_error: write: Broken pipe
Apr 18 03:13:58 servera sshd[1170]: Accepted publickey for root from 172.25.250.9 port 47238 ssh2: RSA SHA256:M8ikhcEDm2tQ95Z0o7ZvufqEixCFCt+wowZLNzNlBT0
Apr 18 03:13:58 servera systemd[1174]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Apr 18 03:13:58 servera sshd[1170]: pam_unix(sshd:session): session opened for user root by (uid=0)
